### ISSUE TITLE
NextTweetStreamAsync don't return errors if connection failed?

### ISSUE THREAD

**Issue by AlexGer123** [Xwilarg/TwitterSharp#8]
Hi,

I try some TwitterSharp calls like "NextTweetStreamAsync". On my local computer it work well.
But if I release this to a server I don't get any tweets and no errors. So I guessed it is a block from my server provider.
So I try a raw call (with RestSharp) like:

```cs
            var client = new RestClient(baseTwitterAPIUrl + "tweets/" + tweetID);
            var request = new RestRequest(Method.GET);
            request.AddHeader("Authorization", "Bearer " + bearerToken);
            IRestResponse response = client.Execute(request);
            if (response.IsSuccessful == false)
            {
                LogRorsat.LoggingRorsat("Error get tweet " + response.IsSuccessful);
                LogRorsat.LoggingRorsat(response.ErrorMessage);
                LogRorsat.LoggingRorsat(response.ErrorException.StackTrace);
            }
```
Log message:
```
2021-12-15 20:01:03.083 +01:00 [INF] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. [::ffff:104.244.42.2]:443 (api.twitter.com:443)
2021-12-15 20:01:03.102 +01:00 [INF]    at System.Net.HttpWebRequest.GetResponse()
   at RestSharp.Http.<ExecuteRequest>g__GetRawResponse|185_1(WebRequest request)
   at RestSharp.Http.ExecuteRequest(String httpMethod, Action`1 prepareRequest)
```
So I think the server blocked my requests...
It is possible to catch the errors with TwitterSharp like RestSharp?
If I take a look at the code:
```cs
        public async Task NextTweetStreamAsync(Action<Tweet> onNextTweet, TweetOption[] tweetOptions = null, UserOption[] options = null, MediaOption[] mediaOptions = null)
        {
            var req = new RequestOptions();
            AddTweetOptions(req, tweetOptions);
            AddUserOptions(req, options, true);
            AddMediaOptions(req, mediaOptions);
            Console.WriteLine(_baseUrl + "tweets/search/stream?" + req.Build());
            var stream = await _httpClient.GetStreamAsync(_baseUrl + "tweets/search/stream?" + req.Build());
            using StreamReader reader = new(stream);
            while (!reader.EndOfStream)
            {
                var str = reader.ReadLine();
                if (string.IsNullOrWhiteSpace(str))
                {
                    continue;
                }
                onNextTweet(ParseData<Tweet>(str).Data);
            }
        }
```
This methode can not return an error right?

**Comment by Xwilarg** [comment]
The method itself does not return anything but you should be able to put the code that is inside the function in a try catch block to see if anything is thrown
